### PR TITLE
Migrate from Newtonsoft.Json to System.Text.Json

### PR DESCRIPTION
**Pull request by cricketthomas**
System.Text has various performance and security improvements and is now included in net core and later versions.
Since this library is only using the serializer, I thought this would be a nice and simple upgrade for the gains of system.text.json.

### CODE REVIEW

**Comment by scgough** [comment]
Hi @cricketthomas - thanks for this and sorry for the delay! Really great to have some community input. 
I've taken a quick look locally but there seems to be an issue specifically with the deserialisation of a string/quoted number for `photographer_id` in the `Photo` model.
I get the error: `Cannot get the value of a token type 'Number' as a string`. Not sure if you've encountered this?

I'll aim to put aside some time to take a more detailed look.

**Comment by cricketthomas** [comment]
Hey, thank you for being open to PRs and for taking a look! 
I haven't encountered that, I am going to further test it. Thanks for catching it.

**Comment by cricketthomas** [comment]
> Hi @cricketthomas - thanks for this and sorry for the delay! Really great to have some community input.
> I've taken a quick look locally but there seems to be an issue specifically with the deserialisation of a string/quoted number for `photographer_id` in the `Photo` model.
> I get the error: `Cannot get the value of a token type 'Number' as a string`. Not sure if you've encountered this?
> 
> I'll aim to put aside some time to take a more detailed look.

Hey, I looked into it and my test project was not referencing the changes I made. 

After looking at it at face value, it seems that the 'photographer_id' property was added as a string, when its listed as an integer in the [documentation](https://www.pexels.com/api/documentation/). I didn't build the API of course, so I presume it was done for a reason? 
If not, I pushed a change to accommodate for this, assuming its appropriate. Not sure how this will fair with other users using the SDK. If not appropriate it, I can reconvert it to a string. 
Thanks!

**Comment by scgough** [comment]
@cricketthomas hi - just wanted to check in and see if we can wrap this PR up. I've taken another look at this and the following should be everything needed to do this:

- The new merged changes will need to be hooked in to the `System.Text.Json` package (Collections endpoints)
- The issue w/ `photographer_id` in `CollectionMedia` should be fixable by changing the type to `int` 

Hopefully once this is done I can test and close off the PR! Let me know if you have any questions.

**Pull request closed without merging**
